on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
      - name: Run build
        uses: matlab-actions/run-build@v2
        with:
          tasks: check test
