on:
  pull_request:
jobs:
  build:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Restore buildtool cache
        uses: actions/cache@v4
        with:
          path: |
            .buildtool
          key: buildtool-${{ github.ref }}
          restore-keys: |
            buildtool-${{ github.ref }}
            buildtool-${{ github.head_ref }}
            buildtool-refs/heads/main
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest-including-prerelease
          products: MATLAB_Test
          cache: true
      - name: Run build
        uses: matlab-actions/run-build@v2
        with:
          tasks: check test(RunOnlyImpacted=true)
